### PR TITLE
Add missing PlayReq enum

### PR DESCRIPTION
**Pull request by shinoi2**
### Add missing PlayReq enum
* REQ_TARGET_IF_AVAILABLE_AND_ONLY_EVEN_COST_CARD_IN_DECK => [GIL_530] Murkspark Eel
* REQ_TARGET_IF_AVAILABLE_AND_ONLY_ODD_COST_CARD_IN_DECK => Guess, not used yet
* REQ_TARGET_IF_AVAILABLE_AND_COST_5_OR_MORE_SPELL_IN_HAND => [DAL_539] Sunreaver Warmage
* REQ_TARGET_IF_AVAILABLE_AND_MIN_MANA_CRYSTAL => [DAL_770] Omega Devastator
* REQ_MINION_ATTACK_LESS_OR_EQUAL_MANA => [DAL_723] Forbidden Words
* REQ_FRIENDLY_LACKEY => [ULD_162] Reclutadora del MAL
* REQ_TARGET_IF_AVAILABLE_AND_FRIENDLY_LACKEY => [UID_170] Weaponized Wasp
* REQ_TARGET_MIN_HEALTH => [ULDA_BOSS_35p] Vengeful Construct

### CODE REVIEW

**Comment by beheh** [comment]
Hey there! I saw you added yourself to the [CLA](https://github.com/HearthSim/cla) repository. I still need your signature  there so I can proceed here. Simply [follow the README](https://github.com/HearthSim/cla?tab=readme-ov-file#signing-the-cla) instructions to create a PR, and we can proceed here.

**Comment by shinoi2** [comment]
Here: https://github.com/HearthSim/cla/pull/62

**Comment by beheh** [comment]
Thanks!

**Comment by beheh** [comment]
Back to this PR, can you let me know how you sourced these values? I can't find any corroborating game files.

**Comment by shinoi2** [comment]
PlayReq has been removed since 16.0.0.37060 [Ref](https://github.com/HearthSim/HearthDb/issues/18)
The last verstion with PlayReq was 15.6.2.36393. [CardDefs.xml](https://raw.githubusercontent.com/HearthSim/hsdata/36393/CardDefs.xml), I find them in this version

**Comment by beheh** [comment]
Ah. In that case I question whether these need to be updated at all? I'd much rather drop them here, as we only really want to support the latest versions of Hearthstone. There's already enough to keep track of without trying to reconstruct the entire history.

**Comment by beheh** [comment]
How about moving PlayReq into Fireplace then instead? Then you can also update it at your own leisure.

**Comment by shinoi2** [comment]
I will move PlayReq into fireplace.

**Pull request closed without merging**
